AllCops:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Security/Open:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/MethodMissingSuper:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

