AllCops:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 30

Style/AsciiComments:
  Enabled: false

# Metrics/AbcSize:
#   Enabled: false

# Metrics/CyclomaticComplexity:
#   Enabled: false

Style/Documentation:
  Enabled: false



# Style/CaseEquality:
#   Enabled: false

# Lint/AmbiguousOperator:
#   Enabled: false

# Naming/PredicateName:
#   Enabled: false
